### ISSUE TITLE
Support for invisible widget type

### ISSUE THREAD

**Issue by justinmayer** [zmh-program/django-turnstile#1]
Thank you, Minghan, for this very useful project. Bravo! 👏 

I would like to use Turnstile's [invisible widget type](https://developers.cloudflare.com/turnstile/reference/widget-types/#invisible), but it is not clear to me how to configure `django-turnstile` to use the [invisible widget type](https://developers.cloudflare.com/turnstile/reference/widget-types/#invisible). Could you possibly provide some guidance?

**Comment by zmh-program** [comment]
First of all, thank you very much for your advice, this is my first issue! 😃 

I browsed the turnstile docs and CloudFlare community, and as you can see, I didn't find anything specific about invisible widgets. 😓
I'm trying to decompile and read the turnstile source code to find something useful. 🤔

Hope everything goes well. 👀

(Sorry, please excuse my English)

**Comment by zmh-program** [comment]
Wait...
I think I found something useful...
![image](https://user-images.githubusercontent.com/112773885/221346328-502ef463-57b4-497a-897e-7fbf7c19d665.png)
![image](https://user-images.githubusercontent.com/112773885/221346212-4604e373-1266-41bb-af52-d2e7cafa4fb9.png)

It looks like it's the param **`size`** 🤔 
Wait for success! 😄

**Comment by zmh-program** [comment]
Yes, that's right!
![image](https://user-images.githubusercontent.com/112773885/221347100-95496f49-4a2b-4764-9ba9-07be96d82c94.png)

I have already successfully implemented an instance, and both the frontend and the backend are fine! 😃

**Comment by zmh-program** [comment]
Let me tell you how you should change your code:
### - Global Configuration
*\<project\>* / settings.py

```python
TURNSTILE_DEFAULT_CONFIG = {
    'size': 'invisible',   # add it
}
```

or
### - Local Configuration
*...* / forms.py

```python
from django import forms


class ExampleForm(forms.Form):
    captcha = CaptchaField(
        label="captcha",
        size="invisible",   # add it
        error_messages={
            "required": "Please enter the captcha field",
            "invalid": "The captcha is incorrect"
        },
    )

```

*Thanks for the issue! If you are also successful, please comment and then I will close the issue~*

**Comment by justinmayer** [comment]
Hey Zhang. I just wanted to say a belated thank-you for responding to my question so quickly and for answering it so thoughtfully and thoroughly. Much, much appreciated! 💕
